//
// stack/ispc/micro-app-aos.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_STACK_ISPC_MICRO_APP_AOS_H
#define ISPC_STACK_ISPC_MICRO_APP_AOS_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
struct edge {
    int32_t v0;
    int32_t v1;
    float data;
    float v0_pt_data[3];
    float v1_pt_data[3];
};


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void edge_compute(int32_t nedges, struct edge * edges);
    extern void edge_gather(int32_t nedges, struct edge * edges, float pt_data[][3], float * edge_data);
    extern void edge_scatter(int32_t nedges, struct edge * edges, float pt_data[][3]);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_STACK_ISPC_MICRO_APP_AOS_H
