//
// stack/ispc/micro-app-soa.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_STACK_ISPC_MICRO_APP_SOA_H
#define ISPC_STACK_ISPC_MICRO_APP_SOA_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
struct graph {
    int32_t v0[10];
    int32_t v1[10];
    float v0_data[10][3];
    float v1_data[10][3];
    float data[10];
};


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void edge_compute(int32_t nedges, struct graph * g);
    extern void edge_gather(int32_t nedges, struct graph * g, float pt_data[][3], float * edge_data);
    extern void edge_scatter(int32_t nedges, struct graph * g, float pt_data[][3]);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_STACK_ISPC_MICRO_APP_SOA_H
